apiVersion: batch/v1
kind: Job

metadata:
  name: wifi-pytest-job-49

spec:
  backoffLimit: 0

  template:
    spec:
      restartPolicy: Never

      containers:
        - name: pytest
          image: vengateshbabu1605/wifi-pytest-advanced:78
          imagePullPolicy: Always

          command: ["python"]
          args:
            - "-m"
            - "pytest"
            - "-v"
            - "-s"
            - "--html=/app/reports/wlan_test_report.html"
            - "--self-contained-html"
            - "--junitxml=/app/reports/junit-results.xml"

          volumeMounts:
            - name: reports-volume
              mountPath: /app/reports

      volumes:
        - name: reports-volume
          persistentVolumeClaim:
            claimName: wifi-pytest-reports-pvc
